// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlrvvjkayqwwpngkvisp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRscnZ2amtheXF3d3BuZ2t2aXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MzM4NTEsImV4cCI6MjA2OTQwOTg1MX0.klBLoUjBfxXtvgqYjA1K_SI5-6SE17iZvquDWZTb1ZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});